### ISSUE TITLE
Crash in signature parser, would like something easier to understand

### ISSUE THREAD

**Issue by robert-olofsson** [dmlloyd/jdk-classfile-preview#15]
Compiling and running the following code crash with 

```
import io.github.dmlloyd.classfile.ClassSignature;

public class Crash {
    public static void main(String[] args) {
	String goodSignature = "Ljava/lang/Object;Ljava/lang/Iterable<LFoo;>;";
	String badSignature = "Ljava/lang/Object;Ljava/lang/Iterable<LFoo;>";

	System.out.println ("Trying to parse good signature");
	ClassSignature.parseFrom (goodSignature);
	System.out.println ("Trying to parse bad signature");
	ClassSignature.parseFrom (badSignature);
    }
}
```

The stack trace looks like:
```
Exception in thread "main" java.lang.StringIndexOutOfBoundsException: Index 44 out of bounds for length 44
	at java.base/jdk.internal.util.Preconditions$1.apply(Preconditions.java:55)
	at java.base/jdk.internal.util.Preconditions$1.apply(Preconditions.java:52)
	at java.base/jdk.internal.util.Preconditions$4.apply(Preconditions.java:213)
	at java.base/jdk.internal.util.Preconditions$4.apply(Preconditions.java:210)
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:98)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:106)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:302)
	at java.base/java.lang.String.checkIndex(String.java:4828)
	at java.base/java.lang.StringLatin1.charAt(StringLatin1.java:46)
	at java.base/java.lang.String.charAt(String.java:1555)
	at io.github.dmlloyd.classfile.impl.SignaturesImpl.referenceTypeSig(SignaturesImpl.java:137)
	at io.github.dmlloyd.classfile.impl.SignaturesImpl.parseClassSignature(SignaturesImpl.java:53)
	at io.github.dmlloyd.classfile.ClassSignature.parseFrom(ClassSignature.java:80)
	at Crash.main(Crash.java:12)
```

The SIOIBE is hard to understand!
I would be fine with a crash, if it was a bit more helpful, perhaps "IllegalArgumentException: invalid signature" and if it could also say "Missing ";" at position 44" then that would be great.

**Comment by dmlloyd** [comment]
Opened upstream bug [JDK-8321540](https://bugs.openjdk.org/browse/JDK-8321540).
